STAGE_ENV = "FIT_BOOTSTRAP_STAGE"
STAGE_GUI = "gui"
FIT_DEBUG_ENABLED = "FIT_DEBUG_ENABLED"

FIT_USER_APP_PATH = "FIT_USER_APP_PATH"
FIT_LOG_APP_PATH = "FIT_LOG_APP_PATH"

APP_LOCK_NAME = "app.lock"

FIT_OS_TYPE = "FIT_OS_TYPE"
FIT_OS_VERSION = "FIT_OS_VERSION"
FIT_USERNAME = "FIT_USERNAME"
FIT_HOST_IP = "FIT_HOST_IP"
FIT_DNS = "FIT_DNS"
