[tool.poetry]
name = "fit--bootstrap"
version = "0.1.0"
description = "FIT Bootstrap Module"
authors = ["FIT Project"]
license = "LGPL-3.0-or-later"
packages = [
    { include = "fit_bootstrap", from = ".", format = "sdist" }
]

include = [
    "fit_assets/mimtproxy/mitmproxy-ca-cert.pem"
]

[tool.poetry.dependencies]
python = ">=3.11,<3.14"

fit-common = {git = "https://github.com/fit-project/fit-common.git", rev = "main"}
fit-assets = {git = "https://github.com/fit-project/fit-assets.git", rev = "main"}
mitmproxy = "10.4.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
